### ISSUE TITLE
NPCs Not spawning anyhow

### ISSUE THREAD

**Issue by AMIDIBOSS** [Shark-vil/background-citizens#10]
I've tried both of the supported maps and none of the NPCs have ever spawned. Settings are "factory", tried with no other addons loaded. Console does not indicate anything of concern. Am I missing something?

**Comment by Shark-vil** [comment]
Is the problem still relevant? Do you have the latest version of the modification?

**Comment by AMIDIBOSS** [comment]
Yes, recently obtained from steam workshop, still can't get the addon to work

**Comment by Shark-vil** [comment]
The system has been updated.  If the problem persists, open a new issue.
