### ISSUE TITLE
Possible Error with Language

### ISSUE THREAD

**Issue by privateryann1** [Shark-vil/background-citizens#100]
**Describe the bug**
You have the language functions shared.. why? It is just creating script errors serverside. As far as I can tell, you only need to check the language on the client. It is doing it on the server realm which is causing a script error

**Situation for the error to occur**
When the server is starting up

**Additional context**
lua/background_npcs_core/config/replics/sh_init

**Comment by Shark-vil** [comment]
> **Describe the bug** You have the language functions shared.. why? It is just creating script errors serverside. As far as I can tell, you only need to check the language on the client. It is doing it on the server realm which is causing a script error
> 
> **Situation for the error to occur** When the server is starting up
> 
> **Additional context** lua/background_npcs_core/config/replics/sh_init

Paste error text.

**Comment by privateryann1** [comment]
```
[background-citizens-1.7.3] addons/background-citizens-1.7.3/lua/background_npcs_core/config/replics/sh_init.lua:8: attempt to index a nil value
  1. GetGameLanguage - addons/background-citizens-1.7.3/lua/background_npcs_core/config/replics/sh_init.lua:8
   2. func - addons/background-citizens-1.7.3/lua/background_npcs_core/config/replics/sh_init.lua:30
    3. Run - lua/includes/modules/hook.lua:241
     4. func - addons/background-citizens-1.7.3/lua/slib_autoloader/sh_background_npcs.lua:199
      5. unknown - lua/includes/modules/hook.lua:241
```

**Comment by Shark-vil** [comment]
Most likely fixed. If the issue persists, open the issue again.
