### ISSUE TITLE
 I shot at the police or killed to npc the cops don't do anything to stop me i don't  wanted any way to fix that. 

### ISSUE THREAD

**Issue by LASERGAMING** [Shark-vil/background-citizens#120]
**Describe the bug**

**Situation for the error to occur**
Describe in detail the situation when the error occurs. Before creating a ticket, check this situation with **OTHER** addons enabled and disabled *(Do not turn off SLIB)*. Complaints in the format "*Your addon is breaking the game, please fix it*" or "*It doesn't work for me*" will be rejected.

**Screenshots or video**
If possible, add a video or screenshots that show the error.

**Desktop:**
 - OS: [e.g. Windows]
 - Version [e.g. 10]

**Additional context**

**Comment by Shark-vil** [comment]
This problem occurs sometimes, but rarely at this moment. Report on recurrences.
