### ISSUE TITLE
npcs do not move

### ISSUE THREAD

**Issue by jeromecastro292** [Shark-vil/background-citizens#132]
**Describe the bug**
NPCs do spawn, however they do not move around the map and just stand in one place with an Idle pose, the only way to get them to move is to bump into them but even then, they still proceed to stand still.

**Situation for the error to occur**
I just loaded into a map, and they do not move. I also tried multiple maps such as Bigcity_Improved and Rp_Southside. I have a custom model module installed that replaces civillian models and have disabled the "Disable Logic" setting.

**Desktop:**
 - Windows 10
 - Not exactly sure, but It is the update that was released on April 13th

**Additional context**
I had uninstalled the addon prior to this, and only reinstalled the addon recently (Not sure how relevant this is)

**Comment by Shark-vil** [comment]
https://github.com/Shark-vil/background-citizens/pull/133

https://github.com/Shark-vil/background-citizens/releases/tag/1.9.3
