### ISSUE TITLE
Addon not using navmesh by default?

### ISSUE THREAD

**Issue by Earu** [Shark-vil/background-citizens#18]
I've went through the code and I can't seem to find any reference to the `navmesh` library, except to check if its loaded, instead of forcing the players to create their own nodes etc, why not just create a base one based on the navmesh automatically ?

Also the update prompts are super annoying, please do something about that.

**Comment by Shark-vil** [comment]
I am thinking about the possibility of creating points in other ways, but this process cannot be done completely automatically.  Main points still have to be set manually.

What prompts are we talking about?  Those that are displayed for the administration?

**Comment by Shark-vil** [comment]
And yes, if a navigation mesh is available, you can increase the distance between points in the instrument, but movement can become more chaotic.

**Comment by Earu** [comment]
I don't see the problem with creating base preset for a map automatically based on the navmesh, in fact I have done that with another NPC system and it works just fine, it's a shame it cannot be implemented in this addon.

The prompts I'm talking about are the update prompts with the changelogs etc...

**Comment by Shark-vil** [comment]
Added - generation using "navmesh"
Added - automatic generation on any map in real time

**Comment by Shark-vil** [comment]
> I don't see the problem with creating a base preset for a map automatically based on the navmesh, in fact I have done that with another NPC system and it works just fine, it's a shame it cannot be implemented in this addon.
> 
> The prompts I'm talking about are the update prompts with the changelogs etc...

Added - generation using "navmesh"
Added - automatic generation on any map in real time
